tools:
    external_code_coverage:
        timeout: 600
        runs: 2
checks:
    php:
        code_rating: true
        duplication: true
        excluded_dependencies:
            - phan/phan
filter:
    paths:
        - 'src/*'
