language: php
cache:
  directories:
    - $HOME/.composer/cache

install:
  - composer install

jobs:
    include:
      - stage: Static Analysis
        php: 7.3
        script: vendor/bin/phpcs
      - stage: Static Analysis
        php: 7.3
        script: vendor/bin/phpstan a
      - stage: Static Analysis
        php: 7.3
        script: vendor/bin/psalm
      - stage: Static Analysis
        php: 7.3
        before_install: pecl install ast
        script: vendor/bin/phan --progress-bar --color

      - stage: Testing
        php: 7.2
        script: vendor/bin/phpunit --coverage-clover=coverage.clover
      - stage: Testing
        php: 7.3
        script: vendor/bin/phpunit --coverage-clover=coverage.clover

      - stage: Mutation Testing
        php: 7.2
        script: vendor/bin/infection --min-msi=100
      - stage: Mutation Testing
        php: 7.3
        script: vendor/bin/infection --min-msi=100
