language: php
php:
  - 7.1
  - nightly
before_script:
  - if [[ $(phpenv version-name) == "nightly" ]]; then composer remove --dev etsy/phan; else pecl install ast; fi
  - make install
script:
  - make test
after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
