language: php
cache:
  directories:
    - $HOME/.composer/cache
branches:
  only:
    - master

install:
  - composer install

jobs:
    include:
      - env: Phan
        php: 7.4
        before_install: pecl install ast
        script: vendor/bin/phan --progress-bar --color

      - env: PHPUnit
        php: 7.4
        script:
          - vendor/bin/phpunit --coverage-clover=coverage.xml
        after_success:
          - bash <(curl -s https://codecov.io/bash)
