language: php
cache:
  directories:
    - $HOME/.composer/cache
branches:
  only:
    - master

install:
  - composer install

jobs:
    include:
      - env: Phan
        php: 7.4
        before_install: pecl install ast
        script: vendor/bin/phan --progress-bar --color

      - env: PHPUnit
        php: 7.4
        script:
          - vendor/bin/phpunit --coverage-clover=build/logs/clover.xml
        after_success:
          - wget https://github.com/php-coveralls/php-coveralls/releases/download/v2.2.0/php-coveralls.phar
          - php php-coveralls.phar
