language: php
cache:
  directories:
    - $HOME/.composer/cache
php:
  - 7.2
  - 7.3
before_script:
  - if [[ $(phpenv version-name) == "nightly" ]]; then composer remove --dev phan/phan; else pecl install ast; fi
  - make install
script:
  - make test
