name: Continuous Integration
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  coding-standards:
    name: Coding Standards
    runs-on: ubuntu-18.04
    steps:
      - name: Install PHP
        uses: shivammathur/setup-php@v1
        with:
          php-version: '7.4'
          extensions: curl, dom, fileinfo, gd, iconv, intl, json, mbstring, xml, zip
      - uses: actions/checkout@master
      - run: composer install --no-progress
      - run: vendor/bin/phpcs --no-colors
